{
 "title": "percentile-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "percentile-latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "percentile-latencies",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.70, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th-percentile-latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "{{method}}--{{uri}}"
    }
   ]
  },
  {
   "title": "sleep-percentile-latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_bucket{method=\"GET\", uri=\"/sleep\"}[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_bucket{method=\"GET\", uri=\"/sleep\"}[1m])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(http_server_requests_bucket{method=\"GET\", uri=\"/sleep\"}[1m])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.70, sum by(le) (rate(http_server_requests_bucket{method=\"GET\", uri=\"/sleep\"}[1m])))",
     "legendFormat": "70%"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_server_requests_bucket{method=\"GET\", uri=\"/sleep\"}[1m])))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "50th-percentile-latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, method, uri) (rate(http_server_requests_bucket[1m])))",
     "legendFormat": "{{{{method}}--{{uri}}}}"
    }
   ]
  },
  { "title": "request-latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "top-10-latencies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum by(method, uri) (rate(http_server_requests_sum[1m])) / sum by(method, uri) (rate(http_server_requests_count[1m])))"
    }
   ]
  },
  {
   "title": "request-latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_sum[1m])) / sum by(method, uri) (rate(http_server_requests_count[1m]))",
     "legendFormat": "{{method}}--{{uri}}"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "top-10-rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(method, uri) (rate(http_server_requests_count[1m])))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method,uri) ( rate(http_server_requests_count[1m]))",
     "legendFormat": "{{method}}--{{uri}}"
    }
   ]
  }
 ]
}