spring:
  application:
    name: poc-observability

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url:  "http://localhost:4318/v1/metrics"
        step: 10s
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
      step: 10s


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'