spring:
  application:
    name: poc-observability-srv

management:
  metrics:
    distribution:
      percentiles:
        all: [0.5,0.7, 0.9, 0.95, 0.99]
      percentiles-histogram:
        all: true
      minimum-expected-value:
        all: 100ms
      maximum-expected-value:
        all: 10s
      slo:
        all: 300ms, 500ms, 1s , 2s

#    tags:
#      department: ${SERVICE_DEPARTMENT:department-poc}
#      service: ${SERVICE_NAME:${spring.application.name}}
#      team: ${SERVICE_TEAM:team-poc}
#      env: ${SERVICE_ENV:dev}
#      region: ${SERVICE_REGION:us-east-1}
#      instance.id: ${SERVICE_INSTANCE_ID:localhost}
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    metrics:
      export:
        url:  "http://localhost:4318/v1/metrics"
        step: 10s
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
      step: 10s


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: "http://localhost:4317/"
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: ${spring.application.name}
        namespace: poc-namespace